Updated ComputeHelper.cs so that it assigns depth to the textures.
Getting the following error in unity:
Assets\Scripts\Compute Helper\ComputeHelper.cs(154,50): error CS1061: 'Texture' does not contain a definition for 'depth' and no accessible extension method 'depth' accepting a first argument of type 'Texture' could be found (are you missing a using directive or an assembly reference?)